apply plugin: 'com.android.application'

def releaseVersionCode = providers.gradleProperty('VERSION_CODE').get().toInteger()
def releaseVersionName = providers.gradleProperty('VERSION_NAME').get()

android {
    namespace 'de.theduffman85.ntfybatch'
    compileSdk 35

    defaultConfig {
        applicationId 'de.theduffman85.ntfybatch'
        minSdk 26
        targetSdk 35
        versionCode releaseVersionCode
        versionName releaseVersionName
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

android.applicationVariants.all { variant ->
    variant.outputs.all {
        outputFileName = "ntfy-batch-v${variant.versionName}-${variant.buildType.name}.apk"
    }
}

dependencies {
    implementation 'androidx.core:core:1.16.0'
}
